import Head from "next/head";

import NavbarComponent from "../../components/NavbarComponent";
import HomePage from "./Home";
import ProjectPage from "./ProjectPage";
import BlogPage from "./BlogPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portofolio - Novin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <HomePage />
      <ProjectPage />
      <BlogPage />
    </>
  );
}
